package dev.buhanzaz.state;

public enum MenuState {
    MAIN_MENU, BACK_MENU, ADD_IMAGE_MENU, SEARCH_IMAGE_MENU, REGISTRATION, DELETE_IMAGE_MENU, SECOND_PHASE_REGISTRATION, FIRST_PHASE_REGISTRATION
}
